title: Healing House
description: Massage therapy clinic in Abbotsford, BC, Canada
baseurl: ""
url: ""
permalink: pretty

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - STRUCTURE.md 