title: Healing House
description: Massage therapy clinic in Abbotsford, BC, Canada
baseurl: ""
url: "www.healinghouseabby.ca"
permalink: pretty

logo: /assets/images/logo.png

# Social media profiles - jekyll-seo-tag will use these
social:
  name: Healing House Massage and Wellness
  links:
    # - https://twitter.com/YourTwitterHandle
    # - https://www.facebook.com/YourFacebookPage
    # - https://www.instagram.com/YourInstagramProfile
    # - https://www.linkedin.com/in/YourLinkedInProfile

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - STRUCTURE.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap # Added for explicit sitemap generation 